#!/usr/bin/env bash
#biggy script

#statics
mgxcmd="../../asterixdb/managix/bin/managix"

#function run
run(){
	read -e -p "biggy>>> " cmd
	history -s "$cmd"
	while [ "$cmd" != "quit" ]
	do
		history -s "$cmd"
		#pre-process cmd
		cmdarr=($cmd)
		#run biggy
		case "${cmdarr[0]}" in
			#input
			"input")
			echo "input..."
			;;
			#store
			"store")
			echo "store..."
			run
			;;
			#compute
			"compute")
			echo "compute..."
			;;
			#control
			"control")
			echo "control..."
			;;
			#output
			"output")
			echo "output..."
			;;
			#commond error
			*)
			echo "Command Error!"
			;;	
		esac	
		#pass cmd to internal
		#newcmd="describe -n mydb"
		#$mgxcmd "$newcmd"
		read -e -p "biggy>>> " cmd
	done
}

if [ "$1" == "install" ]
then 
	#install projects
	echo "installing biggy..."
elif [ "$2" != "biggy" ]
then
	echo "Command Error!"
elif [ "$3" == "" ]
then 
	echo "Command Error!"
else
	#manage biggy
	case "$1" in
		#new
		"new")
		echo "new biggy ""$3""..."
		;;
		#start
		"start")
		echo "start biggy ""$3""..."
		run
		;;
		#stop
		"stop")
		echo "stop biggy ""$3""..."
		;;
		#delete
		"delete")
		echo "delete biggy ""$3""..."
		;;
		#commond error
		*)
		echo "Command Error!"
		;;	
	esac
fi
